
CREATE TABLE IF NOT EXISTS medilinksa_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    access_token LONGTEXT,
    token_type VARCHAR(50),
    userid VARCHAR(50),
    issued VARCHAR(50),
    expires VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS medilinksa_claims (
    id INT AUTO_INCREMENT PRIMARY KEY,
    encounter BIGINT(20) NOT NULL,  
    refno VARCHAR(255),   
    due FLOAT,
    paid FLOAT,    
    claim_data LONGTEXT,
    response_data LONGTEXT,
    trace_data LONGTEXT,   
    reverse_data LONGTEXT,    
    httpcode INT,
    status VARCHAR(255),
    mtype VARCHAR(255),    
    message VARCHAR(255),
    `type` VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP    
);

CREATE TABLE IF NOT EXISTS medilinksa_claims_history (
    id INT AUTO_INCREMENT PRIMARY KEY,
    encounter BIGINT(20) NOT NULL,   
    refno VARCHAR(255),    
    due FLOAT,
    paid FLOAT,    
    claim_data LONGTEXT,
    response_data LONGTEXT,
    trace_data LONGTEXT,    
    reverse_data LONGTEXT,
    httpcode INT,
    status VARCHAR(255),
    mtype VARCHAR(255),    
    message VARCHAR(255),
    `type` VARCHAR(50),
    claim_id BIGINT(20) NOT NULL,    
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP    
);

CREATE TABLE IF NOT EXISTS medilinksa_invoices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pid BIGINT(20) NOT NULL,  
    encounter BIGINT(20) NOT NULL,
    total_amount VARCHAR(255),
    vat_amount VARCHAR(255),  
    total_paid VARCHAR(255),      
    status ENUM('unpaid', 'paid', 'cancelled') DEFAULT 'unpaid',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);



#IfNotColumn users medilinksa_invoice_tax_rate LONGTEXT
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS `medilinksa_invoice_tax_rate` VARCHAR(255);
#EndIf

ALTER TABLE `users` MODIFY COLUMN `npi` VARCHAR(255);

#IfNotColumn insurance_data medilinksa_dep_code VARCHAR(255)
ALTER TABLE `insurance_data` ADD COLUMN IF NOT EXISTS `medilinksa_dep_code` VARCHAR(255);
#EndIf

#IfNotColumn insurance_data medilinksa_desti_code VARCHAR(255)
ALTER TABLE `insurance_data` ADD COLUMN IF NOT EXISTS `medilinksa_desti_code` VARCHAR(255);
#EndIf


CREATE TABLE IF NOT EXISTS `medilinksa_schemes` (
  `id` INT(11)  PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `qedi_code` varchar(255) DEFAULT NULL,
  `desti_code` varchar(255) DEFAULT NULL,
  `scheme_name` varchar(255) DEFAULT NULL,
  `administrator_name` varchar(255) DEFAULT NULL,
  `scheme` varchar(255) DEFAULT NULL
);


INSERT IGNORE INTO `medilinksa_schemes` (`id`, `qedi_code`, `desti_code`, `scheme_name`, `administrator_name`, `scheme`) VALUES
(156, NULL, 'A001', 'AECI', 'MEDSCHEME', 'MediLinkSA'),
(157, NULL, 'A002', 'AECI VALUE', 'UNIVERSAL', 'MediLinkSA'),
(158, NULL, 'A003', 'AFA BROADREACH', 'MEDSCHEME', 'MediLinkSA'),
(159, NULL, 'A004', 'AFA CORPORATE', 'MEDSCHEME', 'MediLinkSA'),
(160, NULL, 'A005', 'AFFINITY HEALTH MED. INS.', 'PAMC (Pan African Managed Care)', 'MediLinkSA'),
(161, NULL, 'A006', 'AFRISAM', 'DISCOVERY', 'MediLinkSA'),
(162, NULL, 'A007', 'Alliance Midmed', 'PHA - Private Health Administrators', 'MediLinkSA'),
(163, NULL, 'A008', 'ALTRON', 'DISCOVERY', 'MediLinkSA'),
(164, NULL, 'A010', 'ANGLO MEDICAL SCHEME', 'DISCOVERY', 'MediLinkSA'),
(165, NULL, 'A011', 'ANGLO VAAL', 'DISCOVERY', 'MediLinkSA'),
(166, NULL, 'A009', 'ANGLO VALUE CARE', 'PRIMECURE', 'MediLinkSA'),
(167, NULL, 'A012', 'AUTO & GENERAL FLEXICARE', 'PRIMECURE', 'MediLinkSA'),
(168, NULL, 'B001', 'BANKMED', 'DISCOVERY', 'MediLinkSA'),
(169, NULL, 'B002', 'BARLOWORLD', 'MEDSCHEME', 'MediLinkSA'),
(170, NULL, 'B003', 'BCIMA (Building & Construction Industry)', 'UNIVERSAL', 'MediLinkSA'),
(171, NULL, 'B004', 'BESTMED', 'BESTMED', 'MediLinkSA'),
(172, NULL, 'B009', 'BESTMED PULSE', 'Enablemed', 'MediLinkSA'),
(173, NULL, 'B006', 'BMW', 'DISCOVERY', 'MediLinkSA'),
(174, NULL, 'B007', 'BONITAS', 'MEDSCHEME', 'MediLinkSA'),
(175, NULL, 'B008', 'BP', 'MMI', 'MediLinkSA'),
(176, NULL, 'C001', 'CAMAF', 'SANLAM HEALTH', 'MediLinkSA'),
(177, NULL, 'C002', 'CAPE MEDICAL PLAN', 'CMP Cape Medical Plan', 'MediLinkSA'),
(178, NULL, 'C003', 'CARECROSS ALL OPTIONS', 'CARECROSS', 'MediLinkSA'),
(179, NULL, 'C004', 'CENTRE FOR DIABETES AND ENDOCRINOLOGY (CDE)', 'SANLAM HEALTH', 'MediLinkSA'),
(180, NULL, 'C005', 'COIDA             ', 'COMPENSATION FUND', 'MediLinkSA'),
(181, NULL, 'C009', 'COIDLINK', 'COIDLINK', 'MediLinkSA'),
(182, NULL, 'C006', 'COMMED', 'MEDSCHEME', 'MediLinkSA'),
(183, NULL, 'C010', 'COMMED ROOTS', 'MEDSCHEME', 'MediLinkSA'),
(184, NULL, 'C007', 'COMPCARE All Options', 'UNIVERSAL', 'MediLinkSA'),
(185, NULL, 'C008', 'COMPSOL', 'COMPSOL', 'MediLinkSA'),
(186, NULL, 'D003', 'DE BEERS', 'DE BEERS ', 'MediLinkSA'),
(187, NULL, 'D004', 'DEEP SOUTH GOLD MINE', 'PROVIDENCE', 'MediLinkSA'),
(188, NULL, 'D001', 'DISCOVERY', 'DISCOVERY', 'MediLinkSA'),
(189, NULL, 'D002', 'DISCOVERY KEYCARE', 'DISCOVERY', 'MediLinkSA'),
(190, NULL, 'D005', 'DOMESTICARE', 'CARECROSS', 'MediLinkSA'),
(191, NULL, 'E001', 'EASIMED A', 'AUH African Unity Health Insurance', 'MediLinkSA'),
(192, NULL, 'E002', 'EDCON', 'DISCOVERY', 'MediLinkSA'),
(193, NULL, 'E006', 'EEBS', 'PAMC (Pan African Managed Care)', 'MediLinkSA'),
(194, NULL, 'E003', 'ELLERINE HOLDINGS', 'MEDSCHEME', 'MediLinkSA'),
(195, NULL, 'E004', 'ENGEN', 'MMI', 'MediLinkSA'),
(196, NULL, 'E005', 'ESSENTIAL MED', 'PAMC (Pan African Managed Care)', 'MediLinkSA'),
(197, NULL, 'F001', 'FEDHEALTH', 'MEDSCHEME', 'MediLinkSA'),
(198, NULL, 'F002', 'FISHMED', 'MMI', 'MediLinkSA'),
(199, NULL, 'G001', 'GEMS  BERYL & SAPPHIRE', 'MHG  (Metropolitan Health Group)', 'MediLinkSA'),
(200, NULL, 'G002', 'GEMS EMERALD  ONYX & RUBY', 'MHG  (Metropolitan Health Group)', 'MediLinkSA'),
(201, NULL, 'G003', 'GENESIS', 'GENESIS ', 'MediLinkSA'),
(202, NULL, 'G011', 'GETSAVVI All Options', 'BLACKBIRD GROUP', 'MediLinkSA'),
(203, NULL, 'G005', 'GLENCORE', 'DISCOVERY', 'MediLinkSA'),
(204, NULL, 'G006', 'GOLD FIELDS SOUTH DEEP GOLD MINE', 'PROVIDENCE', 'MediLinkSA'),
(205, NULL, 'G007', 'GOLDEN ARROW', 'MMI', 'MediLinkSA'),
(206, NULL, 'G008', 'GOMOMO - SIZWE', 'Enablemed', 'MediLinkSA'),
(207, NULL, 'G009', 'GRINTEK', 'UNIVERSAL', 'MediLinkSA'),
(208, NULL, 'G010', 'GROOMS COVER OPTION', 'Enablemed', 'MediLinkSA'),
(209, NULL, 'H002', 'HARMONY GOLD MINE', 'SANLAM HEALTH', 'MediLinkSA'),
(210, NULL, 'H003', 'HEALTH4ME', 'MOMENTUM ', 'MediLinkSA'),
(211, NULL, 'H004', 'HERITAGE HEALTH', 'PHA - Private Health Administrators', 'MediLinkSA'),
(212, NULL, 'H005', 'HORIZON', 'MEDSCHEME', 'MediLinkSA'),
(213, NULL, 'H008', 'HORIZON HOSPITAL PLUS NETWORK', 'CARECROSS', 'MediLinkSA'),
(214, NULL, 'H006', 'HOSMED', 'MEDSCHEME', 'MediLinkSA'),
(215, NULL, 'H007', 'HOSMED ACCESS + ESSENTIAL', 'MEDSCHEME', 'MediLinkSA'),
(216, NULL, 'I001', 'IBM', 'DISCOVERY', 'MediLinkSA'),
(217, NULL, 'I002', 'IMPALA', 'PROVIDENCE', 'MediLinkSA'),
(218, NULL, 'I003', 'IMPERIALMED', 'MMI', 'MediLinkSA'),
(219, NULL, 'I007', 'IMPILO - UNIVERSAL', 'UNIVERSAL', 'MediLinkSA'),
(220, NULL, 'I004', 'IMPRESSIVE DESIGN C', 'AUH African Unity Health Insurance', 'MediLinkSA'),
(221, NULL, 'I006', 'INVESTMED LIMITED', 'PHA - Private Health Administrators', 'MediLinkSA'),
(222, NULL, 'K001', 'KEYHEALTH', 'PPSHA ', 'MediLinkSA'),
(223, NULL, 'K002', 'KEYHEALTH ORIGIN GP + SPECIALIST', 'PRIMECURE', 'MediLinkSA'),
(224, NULL, 'L001', 'LA HEALTH', 'DISCOVERY', 'MediLinkSA'),
(225, NULL, 'L002', 'LA HEALTH KEYCARE', 'DISCOVERY', 'MediLinkSA'),
(226, NULL, 'L003', 'LIBCARE', 'VMED', 'MediLinkSA'),
(227, NULL, 'L004', 'LIBERTY', 'MEDSCHEME', 'MediLinkSA'),
(228, NULL, 'L005', 'LIBERTY TRADITIONAL BASIC', 'PRIMECURE', 'MediLinkSA'),
(229, NULL, 'L006', 'LONMIN', 'DISCOVERY', 'MediLinkSA'),
(230, NULL, 'M017', 'MAKOTI HEALTH PLAN', 'Enablemed', 'MediLinkSA'),
(231, NULL, 'M002', 'MALCOR', 'DISCOVERY', 'MediLinkSA'),
(232, NULL, 'M016', 'MALCOR (plan D)', 'Enablemed', 'MediLinkSA'),
(233, NULL, 'M004', 'MASSMART', 'UNIVERSAL', 'MediLinkSA'),
(234, NULL, 'M005', 'MBMED', 'MEDSCHEME', 'MediLinkSA'),
(235, NULL, 'M015', 'MEDICALL', 'PHA - Private Health Administrators', 'MediLinkSA'),
(236, NULL, 'M006', 'MEDIHELP', 'MEDIHELP', 'MediLinkSA'),
(237, NULL, 'M007', 'MEDIMED', 'PROVIDENCE', 'MediLinkSA'),
(238, NULL, 'M008', 'MEDIONE SICK FUND', 'UNIVERSAL', 'MediLinkSA'),
(239, NULL, 'M009', 'MEDIPOS', 'MHG  (Metropolitan Health Group)', 'MediLinkSA'),
(240, NULL, 'M010', 'MEDSHIELD (nexus)', 'MEDSHIELD', 'MediLinkSA'),
(241, NULL, 'M011', 'METROPOLITAN HEALTH / STAFF', 'MMI', 'MediLinkSA'),
(242, NULL, 'M013', 'MOMENTUM', 'MOMENTUM ', 'MediLinkSA'),
(243, NULL, 'M014', 'MOTO HEALTHCARE', 'MOMENTUM ', 'MediLinkSA'),
(244, NULL, 'M018', 'MOTO HEALTHCARE - CUSTOM', 'CARECROSS', 'MediLinkSA'),
(245, NULL, 'M019', 'MOTO HEALTHCARE - ESSENTIAL', 'CARECROSS', 'MediLinkSA'),
(246, NULL, 'N001', 'NAMIBIA HEALTH PLAN', 'MEDSCHEME NAMIBIA', 'MediLinkSA'),
(247, NULL, 'N002', 'NAMIBIA IND MEDICAL AID', 'MEDSCHEME NAMIBIA', 'MediLinkSA'),
(248, NULL, 'N003', 'NASPERS - MMED', 'DISCOVERY', 'MediLinkSA'),
(249, NULL, 'N011', 'NATIONAL HEALTHCARE', 'NATIONAL HEALTHCARE', 'MediLinkSA'),
(250, NULL, 'N004', 'NBCRFLI', 'PAMC (Pan African Managed Care)', 'MediLinkSA'),
(251, NULL, 'N010', 'NEDGROUP', 'MEDSCHEME', 'MediLinkSA'),
(252, NULL, 'N007', 'NETCARE            ', 'DISCOVERY', 'MediLinkSA'),
(253, NULL, 'N008', 'NIMAS - RESOLUTION HEALTH', 'Knowledge Objects (Agility)', 'MediLinkSA'),
(254, NULL, 'O005', 'OCCUMED', 'CARECROSS', 'MediLinkSA'),
(255, NULL, 'O006', 'OCSACARE', 'CARECROSS', 'MediLinkSA'),
(256, NULL, 'O001', 'OLD MUTUAL STAFF', 'MEDSCHEME', 'MediLinkSA'),
(257, NULL, 'O007', 'OLD MUTUAL STAFF - NETWORK PLAN & SELECT PLAN', 'CARECROSS', 'MediLinkSA'),
(258, NULL, 'O008', 'ONECARE - BESTMED PULSE 2', 'CARECROSS', 'MediLinkSA'),
(259, NULL, 'O003', 'ONECARE - NEDGROUP ', 'MEDSCHEME', 'MediLinkSA'),
(260, NULL, 'O004', 'OPMED', 'OPMED', 'MediLinkSA'),
(261, NULL, 'P001', 'PARMED', 'MEDSCHEME', 'MediLinkSA'),
(262, NULL, 'P002', 'PG GROUP', 'MMI', 'MediLinkSA'),
(263, NULL, 'P003', 'PICK AND PAY', 'MMI', 'MediLinkSA'),
(264, NULL, 'P009', 'PICK AND PAY - PRIMARY OPTION', 'CARECROSS', 'MediLinkSA'),
(265, NULL, 'P004', 'PLATINUM HEALTH    ', 'PLATINUM HEALTH', 'MediLinkSA'),
(266, NULL, 'P010', 'PLATINUM HEALTH - PLATCAP', 'CARECROSS', 'MediLinkSA'),
(267, NULL, 'P005', 'POLMED', 'MEDSCHEME', 'MediLinkSA'),
(268, NULL, 'P006', 'PRIME CARE STUDENT', 'AUH African Unity Health Insurance', 'MediLinkSA'),
(269, NULL, 'P007', 'PROFMED', 'PPSHA ', 'MediLinkSA'),
(270, NULL, 'P008', 'PROTEKTA MEDICAL INSURANCE', 'PROVIDENCE', 'MediLinkSA'),
(271, NULL, 'Q001', 'QUANTUM', 'DISCOVERY', 'MediLinkSA'),
(272, NULL, 'Q002', 'QUANTUM KEYCARE', 'DISCOVERY', 'MediLinkSA'),
(273, NULL, 'R001', 'RAND MUTUAL', 'RAND MUTUAL', 'MediLinkSA'),
(274, NULL, 'R002', 'RANDWATER', 'SANLAM HEALTH', 'MediLinkSA'),
(275, NULL, 'R004', 'REMEDI', 'DISCOVERY', 'MediLinkSA'),
(276, NULL, 'R005', 'RESOLUTION', 'Knowledge Objects (Agility)', 'MediLinkSA'),
(277, NULL, 'R006', 'RETAIL', 'DISCOVERY', 'MediLinkSA'),
(278, NULL, 'R007', 'RUMED ', 'PROVIDENCE', 'MediLinkSA'),
(279, NULL, 'S001', 'SAB', 'DISCOVERY', 'MediLinkSA'),
(280, NULL, 'S002', 'SABC', 'MEDSCHEME', 'MediLinkSA'),
(281, NULL, 'S003', 'SAMWUMED', 'SAMWUMED', 'MediLinkSA'),
(282, NULL, 'S016', 'SAPS MEDICALS INSURANCE', 'CARECROSS', 'MediLinkSA'),
(283, NULL, 'S004', 'SASOLMED', 'MEDSCHEME', 'MediLinkSA'),
(284, NULL, 'S005', 'SEDMED', 'SEDMED', 'MediLinkSA'),
(285, NULL, 'S006', 'SELFMED', 'SELFMED', 'MediLinkSA'),
(286, NULL, 'S017', 'SELFMED - SELFNET', 'CARECROSS', 'MediLinkSA'),
(287, NULL, 'S007', 'SIBANYE GOLD', 'PROVIDENCE', 'MediLinkSA'),
(288, NULL, 'S008', 'SISONKE', 'PROVIDENCE', 'MediLinkSA'),
(289, NULL, 'S009', 'SIZWE', 'Knowledge Objects (Agility)', 'MediLinkSA'),
(290, NULL, 'S010', 'SPECTRAMED', 'Knowledge Objects (Agility)', 'MediLinkSA'),
(291, NULL, 'S011', 'SPES BONA', 'SPES BONA', 'MediLinkSA'),
(292, NULL, 'S013', 'SUREMED EXPLORER', 'PRIMECURE', 'MediLinkSA'),
(293, NULL, 'S014', 'SUREMED HEALTH', 'PROVIDENCE', 'MediLinkSA'),
(294, NULL, 'S015', 'SWAZIMED', 'PHA - Private Health Administrators', 'MediLinkSA'),
(295, NULL, 'T001', 'TFG', 'DISCOVERY', 'MediLinkSA'),
(296, NULL, 'T002', 'THEBEMED', 'PROVIDENCE', 'MediLinkSA'),
(297, NULL, 'T003', 'THLAKANO All options ', 'PRIMECURE', 'MediLinkSA'),
(298, NULL, 'T004', 'TIGER BRANDS', 'UNIVERSAL', 'MediLinkSA'),
(299, NULL, 'T005', 'TOPMED', 'PHA - Private Health Administrators', 'MediLinkSA'),
(300, NULL, 'T006', 'TOPMED NETWORK', 'PHA - Private Health Administrators', 'MediLinkSA'),
(301, NULL, 'T007', 'TRANSMED', 'MOMENTUM ', 'MediLinkSA'),
(302, NULL, 'T008', 'TRANSMED STATE PLUS NETWORK', 'UNIVERSAL', 'MediLinkSA'),
(303, NULL, 'T010', 'TRANSMED STATE PLUS OWN CHOICE', 'TRANSMED', 'MediLinkSA'),
(304, NULL, 'T009', 'TSOGO', 'DISCOVERY', 'MediLinkSA'),
(305, NULL, 'U002', 'UMVUZO STANDRD AND AFF.', 'UNIVERSAL', 'MediLinkSA'),
(306, NULL, 'S012', 'UMVUZO SUPREME + EXTREME', 'UMVUZO ', 'MediLinkSA'),
(307, NULL, 'U007', 'UNITY HEALTH All Options', 'AUH African Unity Health Insurance', 'MediLinkSA'),
(308, NULL, 'U013', 'UNIVERSAL HEATLH ACCIDENT', 'UNIVERSAL', 'MediLinkSA'),
(309, NULL, 'U008', 'UNIVERSAL WELLNESS', 'UNIVERSAL', 'MediLinkSA'),
(310, NULL, 'U009', 'UNIVERSITY OF KZN', 'DISCOVERY', 'MediLinkSA'),
(311, NULL, 'W001', 'WCMAS', 'WITBANK COALFIELDS', 'MediLinkSA'),
(312, NULL, 'W007', 'WCMAS NTSIKA', 'UNIVERSAL', 'MediLinkSA'),
(313, NULL, 'W008', 'WESMART', 'PAMC (Pan African Managed Care)', 'MediLinkSA'),
(314, NULL, 'W002', 'WITSMED (UNIVERSITY OF WITWATERSRAND)', 'DISCOVERY', 'MediLinkSA'),
(315, NULL, 'W003', 'WOOLTRU', 'MOMENTUM ', 'MediLinkSA'),
(316, NULL, 'W009', 'WOOLTRU - CORE ', 'CARECROSS', 'MediLinkSA'),
(317, NULL, 'W010', 'WORKAWAY', 'CARECROSS', 'MediLinkSA'),
(318, NULL, 'W004', 'WORKERPLAN', 'UNIVERSAL', 'MediLinkSA'),
(319, NULL, 'Y001', 'YEBOMED ', 'WITBANK COALFIELDS', 'MediLinkSA');


INSERT IGNORE INTO list_options (list_id, option_id, title, seq, activity, edit_options)
VALUES
('physician_type','3','Accredited Blood and Blood Product Couriers',200,1,1),
('physician_type','4','Chiropractors',201,1,1),
('physician_type','8','Homeopaths',202,1,1),
('physician_type','9','Ambulance Services - Advanced',203,1,1),
('physician_type','10','Anaesthetists',204,1,1),
('physician_type','11','Ambulance Services - Intermediate',205,1,1),
('physician_type','12','Dermatology',206,1,1),
('physician_type','13','Ambulance Services - Basic',207,1,1),
('physician_type','14','General Medical Practice',208,1,1),
('physician_type','15','Specialist Family Medicine',209,1,1),
('physician_type','16','Independent Practice Specialist Obstetrics and Gynaecology',210,1,1),
('physician_type','17','Pulmonology',211,1,1),
('physician_type','18','Independent Practice Specialist Medicine',212,1,1),
('physician_type','19','Gastroenterology',213,1,1),
('physician_type','20','Neurology',214,1,1),
('physician_type','21','Cardiology',215,1,1),
('physician_type','22','Psychiatry',216,1,1),
('physician_type','23','Medical Oncology',217,1,1),
('physician_type','24','Independent Practice Specialist Neurosurgery',218,1,1),
('physician_type','25','Nuclear Medicine',219,1,1),
('physician_type','26','Ophthalmology',220,1,1),
('physician_type','27','Clinical Haemotology',221,1,1),
('physician_type','28','Orthopaedics',222,1,1),
('physician_type','29','Occupational Medicine Independent Practice Specialist ',223,1,1),
('physician_type','30','Otorhinolaryngology',224,1,1),
('physician_type','31','Rheumatology',225,1,1),
('physician_type','32','Paediatrics Independent Practice Specialist ',226,1,1),
('physician_type','33','Paed. Cardiology',227,1,1),
('physician_type','34','Physical Medicine',228,1,1),
('physician_type','35','Emergency Medicine Independent Practice Specialist ',229,1,1),
('physician_type','36','Plastic and Reconstructive Surgery',230,1,1),
('physician_type','37','Medical technology',231,1,1),
('physician_type','38','Diagnostic Radiology',232,1,1),
('physician_type','39','Radiography',233,1,1),
('physician_type','40','Independent Practice Specialist Radiation Oncology',234,1,1),
('physician_type','42','Surgery/Paediatric surgery  Independent Practice Specialist ',235,1,1),
('physician_type','44','Cardio Thoracic Surgery',236,1,1),
('physician_type','46','Urology',237,1,1),
('physician_type','50','Group practices',238,1,1),
('physician_type','51','Group practices/Hospitals',239,1,1),
('physician_type','52','Pathology Independent Practice Specialist',240,1,1),
('physician_type','54','General Dental Practice',241,1,1),
('physician_type','62','Maxillo-facial and Oral Surgery',242,1,1),
('physician_type','64','Orthodontics',243,1,1),
('physician_type','66','Occupational Therapy',244,1,1),
('physician_type','67','Art Therapists',245,1,1),
('physician_type','68','Podiatry',246,1,1),
('physician_type','69','Medical Scientist',247,1,1),
('physician_type','70','Optometrists',248,1,1),
('physician_type','71','Optical dispensers',249,1,1),
('physician_type','72','Physiotherapists',250,1,1),
('physician_type','73','Masseurs',251,1,1),
('physician_type','74','Orthoptists',252,1,1),
('physician_type','75','Clinical technology',253,1,1),
('physician_type','78','Blood transfusion services',254,1,1),
('physician_type','79','Hospices',255,1,1),
('physician_type','80','Nursing Agencies/Home Care Services',256,1,1),
('physician_type','81','Registered Councellors',257,1,1),
('physician_type','82','Speech therapy and Audiology',258,1,1),
('physician_type','83','Hearing Aid Acoustician',259,1,1),
('physician_type','84','Dieticians',260,1,1),
('physician_type','85','Psychometry',261,1,1),
('physician_type','86','Psychologists',262,1,1),
('physician_type','87','Orthotists & Prosthetists',263,1,1),
('physician_type','88','Registered nurses',264,1,1),
('physician_type','89','Social workers',265,1,1),
('physician_type','90','Clinical services',266,1,1),
('physician_type','91','Biokinetics',267,1,1),
('physician_type','92','Periodontics',268,1,1),
('physician_type','93','Dental Technician',269,1,1),
('physician_type','94','Prosthodontic',270,1,1),
('physician_type','95','Dental therapy',271,1,1),
('physician_type','96','Community dentistry',272,1,1),
('physician_type','97','Community health',273,1,1),
('physician_type','98','Oral pathology',274,1,1),
('physician_type','101','Naturopathy',275,1,1),
('physician_type','102','Osteopathy',276,1,1),
('physician_type','103','Phytotherapy',277,1,1),
('physician_type','104','Ayurveda ',278,1,1),
('physician_type','105','Acupuncturist',279,1,1),
('physician_type','106','Therapeutic Aromatherapist',280,1,1),
('physician_type','107','Therapeutic Massage Therapist',281,1,1),
('physician_type','108','Therapeutic Reflexologist',282,1,1);


INSERT IGNORE INTO list_options (list_id, option_id, title, seq, activity, edit_options)
VALUES
('_ActEncounterCode','21','Inpatient Hospital',200,1,1),
('_ActEncounterCode','51','Inpatient psychiatric hospital',201,1,1),
('_ActEncounterCode','61','Inpatient rehabilitation facility',202,1,1),
('_ActEncounterCode','11','Consulting Room',203,1,1),
('_ActEncounterCode','12','Home',204,1,1),
('_ActEncounterCode','22','Hospital outpatient facility',205,1,1),
('_ActEncounterCode','23','Casualty',206,1,1),
('_ActEncounterCode','24','Day clinic / hospital',207,1,1),
('_ActEncounterCode','25','Birthing center',208,1,1),
('_ActEncounterCode','26','Military treatment facility',209,1,1),
('_ActEncounterCode','31','Stepdown',210,1,1),
('_ActEncounterCode','32','Nursing Home',211,1,1),
('_ActEncounterCode','33','Chronic psychiatric facility',212,1,1),
('_ActEncounterCode','34','Hospice',213,1,1),
('_ActEncounterCode','41','Ambulance – Land',214,1,1),
('_ActEncounterCode','42','Ambulance – Air Or Water',215,1,1),
('_ActEncounterCode','50','Not for use in SA-not allowable',216,1,1),
('_ActEncounterCode','52','Acute psychiatric facility',217,1,1),
('_ActEncounterCode','53','Out of hospital mental health clinic',218,1,1),
('_ActEncounterCode','54','Not for use in SA',219,1,1),
('_ActEncounterCode','55','Drug & alcohol rehabilitation',220,1,1),
('_ActEncounterCode','56','Halfway House',221,1,1),
('_ActEncounterCode','62','Outpatient rehabilitation',222,1,1),
('_ActEncounterCode','65','Dialysis Centre',223,1,1),
('_ActEncounterCode','66','Radiotherapy Centre',224,1,1),
('_ActEncounterCode','71','State Or Local Public Health Clinic',225,1,1),
('_ActEncounterCode','72','Rural Health Clinic',226,1,1),
('_ActEncounterCode','81','Private Laboratory',227,1,1),
('_ActEncounterCode','99','Other Unlisted Facility',228,1,1);

